-- Canonical DDL for `sources` and `metrics` — the only two tables the dashboard
-- reads and the only ones the extract-benchmarks skill writes.
--
-- sources: one row per ingested card/paper. The skill upserts by origin_url.
--
-- metrics: one row per (source, model, condition, subset, benchmark) data point.
--   accepted=false on insert; a reviewer flips it to true in review.html.
--   condition = how the *model* was run (reasoning effort, tools, thinking,
--   safeguards, attempts, sampling/scoring like Pass@1/5-shot, training variant).
--   subset    = which *slice of the benchmark* was measured (language, language
--   family, difficulty, topic/harm category, named split, context length, …).
--   category  = the broad family of the *benchmark itself* (Knowledge & Reasoning,
--   Math, Code & Agentic, Multimodal, Multilingual & IF, Cyber, Safety & Refusal,
--   CBRN & Bio, Alignment & Honesty, Other). A property of the benchmark, so all
--   rows sharing a `benchmark` carry the same category; the dashboard groups and
--   filters columns by it. Backfilled by supabase/backfill_categories.py from
--   supabase/benchmark_category_map.csv; new extractions set it in the CSV.
--   section_key = the source's table/figure number (fig_num from the CSV),
--   used to group rows back into their original table for review.
--   page_num = the PDF page the table/figure appears on (1-based); used by
--   review.html to align each group with its rendered page image.
--
-- Run once via the Management API (Dashboard -> SQL editor, or the curl in
-- CLAUDE.md "Keys & secrets"). Idempotent.

create table if not exists public.sources (
    id          bigint generated by default as identity primary key,
    origin_url  text not null
);

do $$ begin
  if not exists (select 1 from pg_constraint
                 where conname='sources_origin_url_key'
                 and conrelid='public.sources'::regclass) then
    alter table public.sources add constraint sources_origin_url_key unique (origin_url);
  end if;
end $$;

alter table public.sources enable row level security;
drop policy if exists sources_read on public.sources;
create policy sources_read on public.sources for select to anon, authenticated using (true);

-- ---

create table if not exists public.metrics (
    id          bigint generated by default as identity primary key,
    source_id   bigint references public.sources(id),
    model       text,
    condition   text    default '',
    subset      text    default '',
    benchmark   text,
    category    text    default '',
    value       text,
    units       text    default '',
    row_idx     integer,
    col_idx     integer,
    section_key text,
    page_num    integer,
    accepted    boolean not null default false
);

alter table public.metrics enable row level security;
drop policy if exists metrics_read on public.metrics;
create policy metrics_read on public.metrics for select to anon, authenticated using (true);

-- The reviewer UPDATE policy (lets review.html flip `accepted`) lives in
-- promote.sql — its single home, so the allowlisted email isn't edited twice.

-- Reconcile an already-existing table to this shape. Idempotent.
alter table public.metrics add column if not exists source_id bigint references public.sources(id);
alter table public.metrics add column if not exists subset text default '';
alter table public.metrics add column if not exists category text default '';
alter table public.metrics drop column if exists source_url;
alter table public.metrics drop column if exists crop_url;
alter table public.metrics drop column if exists section_title;
alter table public.metrics drop column if exists status;
alter table public.metrics add column if not exists page_num integer;
alter table public.sources drop column if exists kind;
alter table public.sources drop column if exists html;
