-- Canonical DDL for `sources` and `metrics` — the only two tables the dashboard
-- reads and the only ones the extract-benchmarks skill writes.
--
-- sources: one row per ingested card/paper. The skill upserts by origin_url.
--   html is nullable: set for HTML sources (stored with <base href> injected so
--   the review page can embed it); null for PDFs (those frame fine directly).
--
-- metrics: one row per (source, model, condition, benchmark) data point.
--   accepted=false on insert; a reviewer flips it to true in review.html.
--   section_key = the source's table/figure number (fig_num from the CSV),
--   used to group rows back into their original table for review.
--
-- Run once via the Management API (Dashboard -> SQL editor, or the curl in
-- CLAUDE.md "Keys & secrets"). Idempotent.

create table if not exists public.sources (
    id          bigint generated by default as identity primary key,
    kind        text not null check (kind in ('html', 'pdf')),
    origin_url  text not null,
    html        text                    -- stored card HTML (null for PDFs)
);

do $$ begin
  if not exists (select 1 from pg_constraint
                 where conname='sources_origin_url_key'
                 and conrelid='public.sources'::regclass) then
    alter table public.sources add constraint sources_origin_url_key unique (origin_url);
  end if;
end $$;

alter table public.sources enable row level security;
drop policy if exists sources_read on public.sources;
create policy sources_read on public.sources for select to anon, authenticated using (true);

-- ---

create table if not exists public.metrics (
    id          bigint generated by default as identity primary key,
    source_id   bigint references public.sources(id),
    model       text,
    condition   text    default '',
    benchmark   text,
    value       text,
    units       text    default '',
    row_idx     integer,
    col_idx     integer,
    section_key text,
    accepted    boolean not null default false
);

alter table public.metrics enable row level security;
drop policy if exists metrics_read on public.metrics;
create policy metrics_read on public.metrics for select to anon, authenticated using (true);

-- The reviewer UPDATE policy (lets review.html flip `accepted`) lives in
-- promote.sql — its single home, so the allowlisted email isn't edited twice.

-- Reconcile an already-existing table to this shape. Idempotent.
alter table public.metrics add column if not exists source_id bigint references public.sources(id);
alter table public.metrics drop column if exists source_url;
alter table public.metrics drop column if exists crop_url;
alter table public.metrics drop column if exists section_title;
alter table public.metrics drop column if exists status;
