-- Canonical DDL for the long-format `metrics` table — the only table the
-- dashboard reads and the only one the extract-benchmarks skill writes.
--
-- One row per (model, condition, benchmark) data point. The skill inserts rows
-- with `accepted = false`; a reviewer signs tables off in review.html, which
-- records the decision in the `reviews` table (see reviews.sql). The dashboard's
-- "trusted only" view is driven by those review decisions, not by `accepted`.
--
-- The source is stored inline as `source_url` (the origin URL of the card/page)
-- — there is no separate `sources` table in the read path. web/common.js selects
-- exactly these columns; keep them in sync.
--
-- Run once via the Management API (Dashboard -> SQL editor, or the curl in
-- CLAUDE.md "Keys & secrets"). Idempotent.

create table if not exists public.metrics (
    id          bigint generated by default as identity primary key,
    source_url  text,                      -- origin URL of the card/page this came from
    model       text,
    condition   text    default '',
    benchmark   text,
    value       text,                      -- kept as printed (preserve precision; e.g. "11/12")
    units       text    default '',
    row_idx     integer,                   -- tables only (graphs leave row/col null)
    col_idx     integer,                   -- tables only
    section_key text,                      -- source table/figure number; groups a table's cells
    accepted    boolean not null default false
);

-- Reconcile an already-existing table to this shape (the live table was created
-- out-of-band and drifted). All idempotent.
alter table public.metrics add column if not exists source_url text;
alter table public.metrics drop column if exists crop_url;
alter table public.metrics drop column if exists section_title;
alter table public.metrics drop column if exists source_id;
alter table public.metrics drop column if exists status;

-- Anon read for the public dashboard. The skill writes with the service_role
-- key, which bypasses RLS, so no insert policy is needed.
alter table public.metrics enable row level security;
drop policy if exists metrics_read on public.metrics;
create policy metrics_read on public.metrics for select to anon, authenticated using (true);
