"""Filesystem layout for run-time artifacts (frozen blobs, crops, the database).

Everything here is gitignored (see .gitignore): it is regenerated by running the
pipeline. ``LLM_METRICS_VAR`` can override the root (used by tests for tmp dirs).
"""

import os
import pathlib

ROOT = pathlib.Path(os.environ.get("LLM_METRICS_VAR", pathlib.Path(__file__).resolve().parents[2] / "var"))
BLOBS = ROOT / "blobs"     # content-addressed frozen sources (P3)
CROPS = ROOT / "crops"     # highlighted crop PNGs
DB_PATH = ROOT / "metrics.sqlite"


def ensure() -> None:
    for d in (ROOT, BLOBS, CROPS):
        d.mkdir(parents=True, exist_ok=True)
